In [1]:
cd ..

/home/byl/Downloads/Program/Github/TFImageSearchWebApp

In [2]:
import pandas as pd
from config import parquet_path

data = pd.read_parquet(parquet_path)
data = data[data['feature'].apply(lambda x: x.size) > 0]

In [3]:
data

,id,gender,masterCategory,subCategory,articleType,baseColour,season,year,usage,productDisplayName,feature
0,15970,Men,Apparel,Topwear,Shirts,Navy Blue,Fall,2011,Casual,Turtle Check Men Navy Blue Shirt,"[0.0, 0.0064879744, 0.0012390767, 0.0, 0.0, 0...."
1,39386,Men,Apparel,Bottomwear,Jeans,Blue,Summer,2012,Casual,Peter England Men Party Blue Jeans,"[0.0, 0.0, 0.036338627, 0.0, 0.0, 0.0, 0.00901..."
2,59263,Women,Accessories,Watches,Watches,Silver,Winter,2016,Casual,Titan Women Silver Watch,"[0.0, 0.02435015, 0.018694768, 0.04335733, 0.0..."
3,21379,Men,Apparel,Bottomwear,Track Pants,Black,Fall,2011,Casual,Manchester United Men Solid Black Track Pants,"[0.0, 0.0, 0.012969385, 0.0, 0.0, 0.0, 0.02235..."
4,53759,Men,Apparel,Topwear,Tshirts,Grey,Summer,2012,Casual,Puma Men Grey T-shirt,"[0.0, 0.010350692, 0.0, 0.0, 0.0, 0.0062514874..."
...,...,...,...,...,...,...,...,...,...,...,...
44441,17036,Men,Footwear,Shoes,Casual Shoes,White,Summer,2013,Casual,Gas Men Caddy Casual Shoe,"[0.0, 0.03474714, 0.0, 0.0, 0.0, 0.053669687, ..."
44442,6461,Men,Footwear,Flip Flops,Flip Flops,Red,Summer,2011,Casual,Lotto Men's Soccer Track Flip Flop,"[0.0, 0.04732248, 0.0, 0.037258595, 0.0, 0.034..."
44443,18842,Men,Apparel,Topwear,Tshirts,Blue,Fall,2011,Casual,Puma Men Graphic Stellar Blue Tshirt,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.057092987, 0...."
44444,46694,Women,Personal Care,Fragrance,Perfume and Body Mist,Blue,Spring,2017,Casual,Rasasi Women Blue Lady Perfume,"[0.0, 0.035333566, 0.020197215, 0.0, 0.0, 0.0,..."
44445,51623,Women,Accessories,Watches,Watches,Pink,Winter,2016,Casual,Fossil Women Pink Dial Chronograph Watch ES3050,"[0.01985278, 0.033369396, 0.0, 0.029252466, 0...."

In [11]:
prods = data.loc[[10,20,30], :].to_dict(orient='records')

In [12]:
prods

[{'id': '9204',
  'gender': 'Men',
  'masterCategory': 'Footwear',
  'subCategory': 'Shoes',
  'articleType': 'Casual Shoes',
  'baseColour': 'Black',
  'season': 'Summer',
  'year': '2011',
  'usage': 'Casual',
  'productDisplayName': 'Puma Men Future Cat Remix SF Black Casual Shoes',
  'feature': array([0.02534976, 0.02365184, 0.01654571, ..., 0.05430767, 0.        ,
         0.03192621], dtype=float32)},
 {'id': '17429',
  'gender': 'Men',
  'masterCategory': 'Accessories',
  'subCategory': 'Watches',
  'articleType': 'Watches',
  'baseColour': 'Black',
  'season': 'Winter',
  'year': '2016',
  'usage': 'Casual',
  'productDisplayName': 'CASIO G-Shock Men Black Digital Watch G-7710-1DR G223',
  'feature': array([0.01416702, 0.02462038, 0.        , ..., 0.03462126, 0.        ,
         0.01674254], dtype=float32)},
 {'id': '37812',
  'gender': 'Men',
  'masterCategory': 'Apparel',
  'subCategory': 'Topwear',
  'articleType': 'Shirts',
  'baseColour': 'Navy Blue',
  'season': 'Summer',
  'year': '2012',
  'usage': 'Formal',
  'productDisplayName': 'John Players Men Navy Blue Shirt',
  'feature': array([0.       , 0.0050821, 0.       , ..., 0.       , 0.       ,
         0.0303424], dtype=float32)}]